### ISSUE TITLE
Referer flavors.me

### ISSUE THREAD

**Issue by hongaar** [Flameeyes/modsec-flameeyes#11]
This one seems to cause problems with some legit sites, i.e. [mine](http://joram.vandenboezem.nl/): try to click 'webdevelopment' ;)

Seems to me that flavors.me is not a bad referer in itself, but since it offers hosted profiles, bad subdomains could be out there. Can we track down which subdomain(s) and block them instead of entire root domain?

**Comment by Flameeyes** [comment]
So this comes from commit 467682769bab3e4df7380567efce80217bf63391 in 2013 (wow!) — at the time the profiles were not coming from subdomains but from the main domain. But I have not seen them in a while so it might be just easy to remove it now. Want to send a pull request? (I'm currently away from my dev pc.)

**Comment by hongaar** [comment]
Thanks, PR coming your way!
