### ISSUE TITLE
Google cannot crawl due to flameeyes_15_robots_validation.conf restriction

### ISSUE THREAD

**Issue by CRCulver** [Flameeyes/modsec-flameeyes#6]
My site disappeared from Google after some recent modsec-flameeyes update, and when I logged into Google Webmaster Tools, it reported that nearly all my pages were blocked with 403 errors. Removing the file flameeyes_15_robots_validation.conf and restarting Apache was enough for Google to be able to fetch my site successfully. So, there must be some problem within that particular file.

Sorry that I cannot provide more details; I'm happy that your package has reduced the loan on my site, but I don't really understand how these rules work exactly.

**Comment by 0sommer066-0** [comment]
OK, are we good?

**Comment by CRCulver** [comment]
As I mentioned, this behavior was resolved for me after following Flameeyes’ instructions, so this can be closed.
